import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../prisma/prisma.service';
import { exec } from 'child_process';
import * as fs from 'fs';
import * as util from 'util';

const execAsync = util.promisify(exec);

@Injectable()
export class ProxyChainService implements OnModuleInit {
    private readonly logger = new Logger(ProxyChainService.name);
    private configPath: string;
    private reloadCommand: string;

    constructor(
        private prisma: PrismaService,
        private configService: ConfigService,
    ) {
        this.configPath = this.configService.get<string>('PROXY_CONFIG_PATH') || '/etc/3proxy/3proxy.cfg';
        // More aggressive: pkill is more reliable for multiple processes
        this.reloadCommand = this.configService.get<string>('PROXY_RELOAD_COMMAND') || 'pkill -9 3proxy; systemctl restart 3proxy';
    }

    async onModuleInit() {
        this.logger.log('Initializing ProxyChainService... Triggering initial config rebuild.');
        await this.rebuildConfig();
    }

    /**
     * Rebuild 3proxy.cfg from database state
     */
    async rebuildConfig() {
        this.logger.log('Rebuilding 3proxy configuration...');

        const sharedPorts = await this.prisma.port.findMany({
            where: {
                isActive: true,
                packageType: { in: ['Normal', 'Medium'] },
                host: { not: '' },
            },
            include: {
                sessions: {
                    where: { status: 'ACTIVE' },
                },
            },
        });

        // 2. Start config content
        let config = `# Auto-generated by ProxyBot
nserver 8.8.8.8
nserver 1.1.1.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
daemon
`;

        // 3. Generate 'users' line
        const allSessions = sharedPorts.flatMap(p => p.sessions);
        const usersList = ['test:CL:test'];
        for (const s of allSessions) {
            usersList.push(`${s.proxyUser}:CL:${s.proxyPass}`);
        }
        config += `users ${usersList.join(' ')}\n`;
        config += `auth strong\n\n`;

        // DIAGNOSTICS: Port 30000 (No Parent)
        config += `# Diagnostics Port (No Upstream Chaining)\n`;
        config += `allow test\n`;
        config += `proxy -p30000\n`;
        config += `flush\n\n`;

        // 4. Generate Port/Chain definitions
        for (const port of sharedPorts) {
            if (port.upstreamHost && port.upstreamPort && port.localPort) {
                config += `auth strong\n`;

                // Allow specific users
                const allowed = ['test'];
                port.sessions.forEach(s => allowed.push(s.proxyUser));
                config += `allow ${allowed.join(',')}\n`;

                const upUser = port.upstreamUser || '';
                const upPass = port.upstreamPass || '';

                if (upUser && upPass) {
                    config += `parent 1000 tcp ${port.upstreamHost} ${port.upstreamPort} ${upUser} ${upPass}\n`;
                } else {
                    config += `parent 1000 tcp ${port.upstreamHost} ${port.upstreamPort}\n`;
                }

                config += `proxy -p${port.localPort}\n`;
                config += `flush\n\n`;
            }
        }

        // 5. Write file
        try {
            // Only write if not on Windows (Dev mode check)
            if (process.platform !== 'win32') {
                await fs.promises.writeFile(this.configPath, config);
                this.logger.log(`Config written to ${this.configPath}`);

                // 6. Reload service
                await execAsync(this.reloadCommand);
                this.logger.log('3proxy service reloaded');
            } else {
                this.logger.log('Windows Environment detected. Skipping file write/reload. Config content:\n' + config);
            }
        } catch (error) {
            this.logger.error(`Failed to update 3proxy: ${error.message}`);
            // Don't throw, as it might block the main flow. Just log error.
        }
    }
}
